mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  config-location:
    - classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_learning?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root